### ISSUE TITLE
Cannot compile on Mac OS X 10.7.3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kometbomb/klystrack#88]
```
Since there are no nightly builds for OS X, I tried compiling it myself but I 
can't do it. I got this error from make:

src/lib/ksnd.c:1: error: CPU you selected does not support x86-64 instruction 
set
```

Original issue reported on code.google.com by `erdav...@gmail.com` on 29 Apr 2012 at 3:20
